type Field = {
  value: number;
  victoryPoints: number;
  ruby: boolean;
};

const Pot: Field[] = [
  { value: 0, victoryPoints: 0, ruby: false },
  { value: 1, victoryPoints: 0, ruby: false },
  { value: 2, victoryPoints: 0, ruby: false },
  { value: 3, victoryPoints: 0, ruby: false },
  { value: 4, victoryPoints: 0, ruby: false },
  { value: 5, victoryPoints: 0, ruby: true },
  { value: 6, victoryPoints: 1, ruby: false },
  { value: 7, victoryPoints: 1, ruby: false },
  { value: 8, victoryPoints: 1, ruby: false },
  { value: 9, victoryPoints: 1, ruby: true },
  { value: 10, victoryPoints: 2, ruby: false },
  { value: 11, victoryPoints: 2, ruby: false },
  { value: 12, victoryPoints: 2, ruby: false },
  { value: 13, victoryPoints: 2, ruby: true },
  { value: 14, victoryPoints: 3, ruby: false },
  { value: 15, victoryPoints: 3, ruby: false },
  { value: 16, victoryPoints: 3, ruby: false },
  { value: 16, victoryPoints: 4, ruby: false },
  { value: 17, victoryPoints: 4, ruby: false },
  { value: 17, victoryPoints: 4, ruby: true },
  { value: 18, victoryPoints: 4, ruby: false },
  { value: 18, victoryPoints: 5, ruby: false },
  { value: 19, victoryPoints: 5, ruby: false },
  { value: 19, victoryPoints: 5, ruby: true },
  { value: 20, victoryPoints: 5, ruby: false },
  { value: 20, victoryPoints: 6, ruby: false },
  { value: 21, victoryPoints: 6, ruby: false },
  { value: 21, victoryPoints: 6, ruby: true },
  { value: 22, victoryPoints: 7, ruby: false },
  { value: 22, victoryPoints: 7, ruby: true },
  { value: 23, victoryPoints: 7, ruby: false },
  { value: 23, victoryPoints: 8, ruby: false },
  { value: 24, victoryPoints: 8, ruby: false },
  { value: 24, victoryPoints: 8, ruby: true },
  { value: 25, victoryPoints: 9, ruby: false },
  { value: 25, victoryPoints: 9, ruby: true },
  { value: 26, victoryPoints: 9, ruby: false },
  { value: 26, victoryPoints: 10, ruby: false },
  { value: 27, victoryPoints: 10, ruby: false },
  { value: 27, victoryPoints: 10, ruby: true },
  { value: 28, victoryPoints: 11, ruby: false },
  { value: 29, victoryPoints: 11, ruby: false },
  { value: 29, victoryPoints: 12, ruby: false },
  { value: 30, victoryPoints: 12, ruby: false },
  { value: 30, victoryPoints: 12, ruby: true },
  { value: 31, victoryPoints: 12, ruby: false },
  { value: 31, victoryPoints: 13, ruby: false },
  { value: 32, victoryPoints: 13, ruby: false },
  { value: 32, victoryPoints: 13, ruby: true },
  { value: 33, victoryPoints: 14, ruby: false },
  { value: 33, victoryPoints: 14, ruby: true },
  { value: 35, victoryPoints: 15, ruby: false },
];
